name: Publicación de Versión (Firma y Release)

on:
  push:
    branches:
      - master # Se activa automáticamente cada vez que subes algo a master
  workflow_dispatch: # Mantiene el botón manual en la web por si acaso

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: windows-latest

    steps:
    - name: Descargar código
      uses: actions/checkout@v4

    - name: Configurar .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Compilar, Firmar y Empaquetar
      shell: pwsh
      env:
        MY_GITHUB_SECRET_PASSWORD: ${{ secrets.CERT_PASSWORD }}
      run: |
        ./.deploys/BUILD_AND_SIGN.ps1

    - name: Crear GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          *-Windows.zip
          *.zip
        tag_name: v1.0.${{ github.run_number }}
        name: Release v1.0.${{ github.run_number }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}