name: Publicación de Versión (Firma y Release)

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: windows-latest

    steps:
    - name: Descargar código
      uses: actions/checkout@v4

    - name: Configurar .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Compilar y Firmar Ejecutables
      shell: pwsh
      run: |
        ./.local/BUILD_AND_SIGN.ps1

    - name: Crear archivo ZIP
      shell: pwsh
      run: |
        # Nombre corregido a IterVC
        Compress-Archive -Path ./IterVC.Desktop/publish_output/* -DestinationPath ./IterVC-Windows.zip

    - name: Crear GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        files: IterVC-Windows.zip # Nombre corregido a IterVC
        name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}